# Linear algebra with `NumPy`

## Programming and Data Management (EDI 3400)

### *Vegard H. Larsen (Department of Data Science and Analytics)*

# 1. Introduction to NumPy

## What is NumPy (short for Numerical Python)?

- A library that supports large, multi-dimensional **numerical** arrays and matrices, and a large collection of functions for these objects
- NumPy is a cornerstone in the scientific Python community, and most other scientific packages rely on NumPy to work
- Most types of data we will ever encounter can be represented as numerical arrays and matrices, and that includes
    * Collections of documents
    * Collections of images and videos
    * Collections of sound clips
- NumPy arrays provides `list` like functionality but NumPy is much faster, more scalable and more efficient than a regular `list`

## Importing NumPy

In [1]:
import numpy
numpy.__version__

'1.23.1'

In [2]:
# The standard convention for importing NumPy is by using the keyword np

import numpy as np

In [3]:
# Then we can access the functionality of the library through this keyword.  
# We can create an NumPy array from a regular list as follows:

x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [4]:
# We now have a new type of container

type(x)

numpy.ndarray

## Speed test: NumPy vs. Python list

In [5]:
import numpy as np

python_list = list(range(10_000_000)) # [0, 1, 2, ..., 9 999 999]
numpy_array = np.arange(10_000_000)   # np.array([0, 1, 2, ..., 9 999 999])

- Let's multiply all the numbers by 5 and check how long it takes

In [6]:
%timeit python_list5 = [x * 5 for x in python_list]

375 ms ± 29.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%timeit numpy_array5 = numpy_array*5

4.13 ms ± 16.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 2. Working with NumPy arrays

## The NumPy Array Object (`ndarray`)

- A multidimensional container of items of the **same type**
- A ndarray can be accessed and modified by indexing or slicing such as regular lists
- We can use several built-in methods and attributes that belongs to the ndarray object

## Let us create a one-dimensional numpy-array

- Make sure all the values are numeric

In [14]:
# A one dimensional array

numpy_array = np.array([-1, 4, -3, 10, 7, 3.0, 8, 10])
print(numpy_array)
numpy_array.dtype # the type of the elements in the array

[-1.  4. -3. 10.  7.  3.  8. 10.]


dtype('float64')

In [18]:
# It is possible to add different types,
# but then we will lose most advantages of using Numpy

numpy_array_with_different_types = np.array([-1.5, 4.0, 'j', 10, 7.99, 3, 8, 'hello!'])
print(numpy_array_with_different_types)
numpy_array_with_different_types.dtype

['-1.5' '4.0' 'j' '10' '7.99' '3' '8' 'hello!']


dtype('<U32')

In [19]:
# You can convert an array of strings into an array of floats (with NaNs) 

numpy_array_numerics = np.genfromtxt(numpy_array_with_different_types)
numpy_array_numerics.sort()
print(numpy_array_numerics)
numpy_array_numerics.dtype


[-1.5   3.    4.    7.99  8.   10.     nan   nan]


dtype('float64')

## The dimensions of the `ndarray`

In [20]:
# What is the dimensions of this ndarray?

numpy_array = np.array([-1.5, 4.0, -3, 10, 7.99, 3, 8, 9])
print(numpy_array.shape)

(8,)


In [21]:
# Alternatively, we can use two sets of brackets

numpy_array_alt = np.array([[-1.5, 4.0, -3, 10, 7.99, 3, 8, 9]])
print(numpy_array_alt.shape)

(1, 8)


## Two-dimensional arrays

- When the array has more than one dimension, the shape of the array is given as $$rows * columns$$ 

An example of an $3 * 4$ matrix:

|        | column 0 | column 1  | column 2  | column 3  |
|---     |---       |---|---|---|
| row 0  | 10       | 12        | 14        | 16        |
| row 1  | 10.5     | 12.5      | 14.5      | 16.5      |
| row 2  | 11       | 13        | 15        | 17        |     

## Let's create this $3*4$ matrix in NumPy

In [28]:
three_times_four = np.array([[10, 12, 14, 16,],
                             [10.5, 12.5, 14.5, 16.5],
                             [11, 13, 15, 17]])

In [29]:
print(three_times_four)

[[10.  12.  14.  16. ]
 [10.5 12.5 14.5 16.5]
 [11.  13.  15.  17. ]]


In [30]:
# What is the shape of the array?

three_times_four.shape

(3, 4)

In [31]:
# The type of the elements of the array

three_times_four.dtype

dtype('float64')

## We could have started with a one-dimensional array

In [38]:
a = np.array([10, 12, 14, 16, 10.5, 12.5, 14.5, 16.5, 11, 13, 15, 17])
a.shape

(12,)

In [47]:
# And we can set the dimensions as a tuple

a.shape = (3, 4)  # let's try using -1 as one of the elements in the tuple 

In [48]:
a

array([[10. , 12. , 14. , 16. ],
       [10.5, 12.5, 14.5, 16.5],
       [11. , 13. , 15. , 17. ]])

In [49]:
a.shape

(3, 4)

## Accessing the elements of `a`

In [50]:
# Accessing the first (0th) row

a[0]

array([10., 12., 14., 16.])

In [51]:
# Accessing the last column

a[:, 3] # all the rows in the last (3rd) column (can also use -1)

array([16. , 16.5, 17. ])

In [52]:
# Accessing the element in the 1st row and 2nd column (14.5)

a[1, 2]

14.5

## The `ndarray` is mutable and we can change the values  

In [53]:
a[2, 2] = 100  # the previous value was 15

In [54]:
a

array([[ 10. ,  12. ,  14. ,  16. ],
       [ 10.5,  12.5,  14.5,  16.5],
       [ 11. ,  13. , 100. ,  17. ]])

## Slicing and indexing work as with regular lists

In [58]:
# Select the last two rows and the last two columns

a[1:3, 2:4] # Remember the endpoint in the slice is non-inclusive

array([[ 14.5,  16.5],
       [100. ,  17. ]])

In [ ]:
# Alternatively
a[1:, 2:]

## In class exercises 1 (we will do this together in class)

1. Create a one-dimensional array containing the numbers 100, 200, 300 and 400

2. Create a new array from the one-dimensional array that contains the two elements (200 and 300)

3. Create the following $2*2$ matrix:

$$\left[\begin{matrix}
 2 & 8 \\
 1 & 0
\end{matrix}\right]$$

4. Change the value 8 in the $2*2$-matrix to a 4

5. Create a new array that only contains the second column of the $2*2$ matrix

# 3. NumPy methods

## Some special array methods

In [59]:
# A range of numbers (similar to the range() function, but for Numpy arrays)

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# A matrix of zeros (4 rows and 4 columns)

np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
# A matrix of ones (2*2)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [63]:
# The identity matrix

np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Arithmetic operations with NumPy

In [64]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a.shape = 4, 3

In [65]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Multiplying the elements  (element wise multiplication)

In [66]:
a * a

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

### Adding elements 

In [67]:
a + a 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

### Rise all elements to the power of 3

In [68]:
a ** 3

array([[   1,    8,   27],
       [  64,  125,  216],
       [ 343,  512,  729],
       [1000, 1331, 1728]])

## Some more array functions 

#### Make a matrix one dimensional with the `ravel`  method

In [69]:
A = np.array([[2, 3, 4],
              [14, 10, 6]])
A.shape

(2, 3)

In [72]:
A_flattened = A.ravel()

In [71]:
# ravel() does not change the original matrix

A

array([[ 2,  3,  4],
       [14, 10,  6]])

## Random numbers with Numpy

In [76]:
# random integers below a given value (here I use 10)

rand_ints = np.random.randint(1000, size=(10))
print(rand_ints)

[181 489 120 115 846 772 575 584 762 937]


In [77]:
# random samples from a uniform distribution over [0, 1)

rand_floats = np.random.rand(3,3)
print(rand_floats)

[[0.04819092 0.35341831 0.93669764]
 [0.22322728 0.75301992 0.19005446]
 [0.51497692 0.01116669 0.9181811 ]]


## Return an array drawn from the "standard normal" distribution.



In [90]:
x = np.random.randn(1000, 1)
#print(x)

In [91]:
# Calculate the mean of the numbers

np.mean(x)

-0.02176934607376081

In [92]:
# Calculate the standard deviation of the numbers

np.std(x)

0.9968709791346603

## We can also use random choice with Numpy

In [97]:
def drawRandomCard():
    '''
    This function returns a random card from a deck of 52 cards.
    '''
    card_value = np.random.choice(
        ['J', 'Q', 'K', 'A'] + [str(i+2) for i in range(9)]
    )

    card_suit = np.random.choice(
        ['Heart', 'Diamonds', 'Clubs', 'Spades']
    )

    return card_suit + '-' + card_value

In [101]:
drawRandomCard()

'Heart-8'

## Numpy methods

In [103]:
rand_ints = np.random.randn(10)

In [104]:
# Sorting the array

rand_ints.sort()
print(rand_ints)

[-1.51638261 -1.15209275 -0.89516545 -0.89179931 -0.87673188 -0.72039805
  0.24832835  0.66278962  1.30338413  1.39311502]


## Working with NaNs

In [105]:
rand_ints = np.random.randn(10)
rand_ints[3] = np.nan
rand_ints

array([ 0.03265428, -1.7009083 , -1.8975688 ,         nan,  0.10568329,
       -0.09839648, -0.56135918,  1.11911149,  0.14790183,  0.2616981 ])

In [106]:
type(rand_ints[3])

numpy.float64

In [107]:
# Operations with a nan always returns a nan

rand_ints[3]*3

nan

In [108]:
# We can convert the nans to zeros

np.nan_to_num(rand_ints)

array([ 0.03265428, -1.7009083 , -1.8975688 ,  0.        ,  0.10568329,
       -0.09839648, -0.56135918,  1.11911149,  0.14790183,  0.2616981 ])

## In class exercises 2

1. Use the drawRandomCard() function and simulate many draws. Then calculate how many times you get a Spades-A (Ace of Spades) divided by the total number of tries (this gives the estimated probability of drawing the Ace of Spades)
        a. Try with 1000 simulations
        b. Try with 1 000 000 simulations

     (The probability of getting a Spades-A is: $1/52\approx0.01923$)
     

2. Create a 1-dimensional matrix with 18 random numbers (from the standard normal distribution)

3. From this 1-dimensional matrix create one $2*9$ and one $6*3$ matrix

# 4. Linear algebra with NumPy

## Let's have a brief look at some methods for linear algebra

- NumPy is a Python library for linear algebra. Most of what NumPy is used for is beyond the scope of this course, but let's have a quick look at some more advanced futures.  

- Let us define two square matrices $(2*2)$

In [9]:
# Using the method reshape does the same as A.shape = (2, 2) 

A = np.array([1, 2, 3, 4]).reshape((4,1)) 


B = np.array([2, 4, 6, 8]).reshape((2,2)) 

In [11]:
print('The A matrix:')
print(A)
print('')
print('The B matrix')
print(B)

The A matrix:
[[1]
 [2]
 [3]
 [4]]

The B matrix
[[2 4]
 [6 8]]


### The transpose of a matrix
   - The transpose of a matrix is found by interchanging its rows into columns or columns into rows.

In [5]:
A

array([[1, 2],
       [3, 4]])

In [112]:
A.T

array([[1, 3],
       [2, 4]])

### Matrix multiplication (dot-product)
- Matrix multiplication means a row-by-column multiplication, where the entries in the $i$th row of $A$ are multiplied by the corresponding entries in the $j$th column of $B$ and then adding the results.

$A = \left[\begin{matrix}
 A_{11} & A_{12} \\
 A_{21} & A_{22}
\end{matrix}\right]= \left[\begin{matrix}
 1 & 2 \\
 3 & 4
\end{matrix}\right]\;\;$ and $\;\;B = \left[\begin{matrix}
 B_{11} & B_{12} \\
 B_{21} & B_{22}
\end{matrix}\right]= \left[\begin{matrix}
 2 & 4 \\
 6 & 8
\end{matrix}\right]$

We want to compute

$C = AB = \left[\begin{matrix}
 C_{11} & C_{12} \\
 C_{21} & C_{22}
\end{matrix}\right]$

Let's compute $C$

$C_{11} = (A_{11}*B_{11}) + (A_{12}*B_{21}) = (1*2) + (2*6) = 14$

$C_{12} = (A_{11}*B_{12}) + (A_{12}*B_{22}) = (1*4) + (2*8) = 20$

$C_{21} = (A_{21}*B_{11}) + (A_{22}*B_{21}) = (3*2) + (4*6) = 30$

$C_{22} = (A_{21}*B_{12}) + (A_{22}*B_{22}) = (3*4) + (4*8) = 44$

### Let's calculate the whole C-matrix using NumPy:

In [12]:
# There are several ways of computing the dot product
import numpy as np

np.dot(A, B)

ValueError: shapes (4,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [7]:
# Alternative syntax 2

A.dot(B)

array([[14, 20],
       [30, 44]])

In [116]:
# Alternative syntax 3

A @ B

array([[14, 20],
       [30, 44]])

### The matrix inverse 

- If $A$ is a square matrix and $B$ is its inverse, then the product of two matrices is equal to the identity matrix.

In [13]:
invB = np.linalg.inv(B)

In [14]:
invB

array([[-1.  ,  0.5 ],
       [ 0.75, -0.25]])

In [16]:
# The dot product of B and invB is the identity matrix

np.dot(B, invB)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## In class exercises 3

1. Create a $(4*4)$ identity matrix

2. Calculate the inverse of this matrix.

3. Create a $(4*4)$ matrix of ones and multiply it by 5 (do a regular multiplication with $*$, and don't use matrix multiplication, @)

4. Multiply the identity matrix with this new matrix. Try with both $*$ (element wise multiplication) and $@$ (matrix multiplication)

5. Try to calculate the inverse of the matrix that has only fives

## Example: Solving a linear equation system

$y + 3z = 29$

$4y - 2z = -10$

This can be written as:

$A\mathbf{x}=b\;\;$
where 
$\;\;A = \left[\begin{matrix}
 1 & 3 \\
 4 & -2
\end{matrix}\right]$,
$\;\;\mathbf{x} = \left[\begin{matrix}
y \\
z
\end{matrix}\right]\;\;$ and $\;\;b = \left[\begin{matrix}
29 \\
-10 
\end{matrix}\right]$

The solution to the system is

$\mathbf{x} = A^{-1}b$

## Solving the equation system with NumPy

In [21]:
A = np.array([[5, 5],
              [5, 5]])

b = np.array([[10], [20]])

In [22]:
print(A.shape)
print(b.shape)

(2, 2)
(2, 1)


In [23]:
# Solution 1:

solu1 = np.linalg.inv(A) @ b

solu1

LinAlgError: Singular matrix

In [20]:
# Solution 2:

solu2 = np.linalg.solve(A, b)

solu2

array([[2.],
       [9.]])